### MATEMÁTICA APLICADA À CIÊNCIA DE DADOS
**Aluno**: Halisson Souza Gomides

**Prontuário**: CP3016382

Lista de exercício sobre matrizes: https://moodle.cmp.ifsp.edu.br/pluginfile.php/87852/mod_resource/content/1/Lista%206.pdf

In [56]:
import numpy as np

#### 1 – (FGV-2005) As meninas 1 = Adriana; 2 = Bruna e 3 = Carla falam muito ao telefone entre si. A matriz M mostra cada elemento aij representando o número de telefonemas que “i” deu para “j” no mês de setembro. . Quem mais telefonou e quem mais recebeu ligações?

In [ ]:
M = np.matrix('0 13 10; 18 0 6; 9 12 0')
print(M)

[[ 0 13 10]
 [18  0  6]
 [ 9 12  0]]


In [ ]:
meninas = np.array(["Adriana","Bruna", "Carla"])
meninas

array(['Adriana', 'Bruna', 'Carla'], dtype='<U7')

In [ ]:
# Quem mais telefonou

idxmaxval = M.sum(axis=1).argmax() # obtem o indice do maior valor da soma ao longo das colunas de cada linha ("i")
print(f'Quem mais telenonou foi: {meninas[idxmaxval]}')

Quem mais telenonou foi: Bruna


In [ ]:
# Quem mais recebeu ligações

idxmaxval = M.sum(axis=0).argmax() # obtem o indice do maior valor da soma ao longo das linhas de cada coluna ("j")
print(f'Quem mais recebeu ligações foi: {meninas[idxmaxval]}')

Quem mais recebeu ligações foi: Adriana


#### 2 – Uma matriz A é do tipo 3 x 5, outra matriz B é do tipo 5 x 2 e a matriz C é do tipo m x 4. Qual o valor de m para que exista o produto (A.B).C? 


So é possével multiplicar duas matrizes se o numero de colunas
da primeira matriz (A) for igual ao numero de linhas da 
segunda matriz (B). A matriz resultante tem o mesmo numero
de linhas da matriz A e o mesmo numero de colunas da matriz B.

Sabendo disso temos que `(A.B) = matriz do tipo 3x2`
Assim sendo, para que exista o produto (A.B).C , `m` deve ser igual a `2`

#### 3 – Dadas as matrizes A e B, obtenha X tal que X.A = B.

In [ ]:
A = np.array([[3,5], [1,-3]])
print(A)

[[ 3  5]
 [ 1 -3]]


In [ ]:
B = np.array([4,0])
print(B)

[4 0]


In [ ]:
X = np.linalg.solve(A,B)
print(X)

[0.85714286 0.28571429]


In [ ]:
# Checando se a solução está correta
np.allclose(np.dot(A, X), B)

True

#### 4 - (FGV-2004) Uma matriz X possui elementos cuja soma vale 1. Se X.[[1,-1],[-1,1]].Xt = [1], onde Xt é a transposta de X, calcule o produto dos elementos de X.

Segue o desenvolvimento da resposta:

![equation](https://latex.codecogs.com/svg.image?%5Ctextbf%7BX%7D%5Ccdot%20%5Cbegin%7Bbmatrix%7D1%20&%20-1%20%5C%5C-1%20&%201%20%5C%5C%5Cend%7Bbmatrix%7D%5Ccdot%20%5Ctextbf%7BX%7D%5E%7BT%7D=%5B1%5D%20)

![equation](https://latex.codecogs.com/svg.image?%5Cbegin%7Bbmatrix%7Da%20&%20b%20%5C%5C%5Cend%7Bbmatrix%7D%5Ccdot%20%5Cbegin%7Bbmatrix%7D1%20&%20-1%20%5C%5C-1%20&%201%20%5C%5C%5Cend%7Bbmatrix%7D%5Ccdot%5Cbegin%7Bbmatrix%7Da%20%5C%5Cb%5Cend%7Bbmatrix%7D=%5Cbegin%7Bbmatrix%7D1%5Cend%7Bbmatrix%7D%20)

![equation](https://latex.codecogs.com/svg.image?%5Cbegin%7Bbmatrix%7Da-b%20&%20-a&plus;b%20%5C%5C%5Cend%7Bbmatrix%7D%5Ccdot%5Cbegin%7Bbmatrix%7Da%20%5C%5Cb%5Cend%7Bbmatrix%7D=%5Cbegin%7Bbmatrix%7D1%5Cend%7Bbmatrix%7D%20)

![equation](https://latex.codecogs.com/svg.image?%5Cbegin%7Bbmatrix%7Da%5E2-ab%20&%20-ab&plus;b%5E2%20%5C%5C%5Cend%7Bbmatrix%7D=%5Cbegin%7Bbmatrix%7D1%5Cend%7Bbmatrix%7D%20)

![equation](https://latex.codecogs.com/svg.image?%5Cbegin%7Bpmatrix%7D%20a&%20-b%20%5C%5C%5Cend%7Bpmatrix%7D%5E%7B2%7D=1%20)

![equation](https://latex.codecogs.com/svg.image?%5Cleft%5C%7B%5Cbegin%7Bmatrix%7Da&plus;b=1%20%5C%5Ca-b=1%20%5C%5Ca-b=-1%20%5C%5C%5Cend%7Bmatrix%7D%5Cright.%20)

![equation](https://latex.codecogs.com/svg.image?%5CRightarrow%20%5Cleft%5C%7B%5Cbegin%7Bmatrix%7Da=1%20%5C%5Cb=0%5Cend%7Bmatrix%7D%5Cright.%5CRightarrow%20a%5Ccdot%20b=0%20)

#### 5 Determine x e y na igualdade:

x-1 = 4
x = 5

2y = -6
y= -3

#### 6 - Dadas as matrizes A e B, determine A + 2.BT


In [ ]:
A = np.array([[1,2,-3], [4,5,6]])
print(A) 

[[ 1  2 -3]
 [ 4  5  6]]


In [ ]:
B = np.array([[1,-2], [3,0], [4,-3]])
print(B) 

[[ 1 -2]
 [ 3  0]
 [ 4 -3]]


In [ ]:
B.T

array([[ 1,  3,  4],
       [-2,  0, -3]])

In [ ]:
resultado = A + np.multiply(2, B.T)
resultado

array([[3, 8, 5],
       [0, 5, 0]])

#### 7- (PUC) Um batalhão do exército, resolveu codificar suas mensagens através da multiplicação de matrizes. Primeiramente, associa as letras do alfabeto aos números, segundo a correspondência abaixo considerada:
A B C D E F G H I   J   L  M  N  O  P  Q  R  S  T  U  V  W  X  Y  Z

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25

Desta forma, utilizando-se a mesma matriz-chave C, a decodificação da mensagem
51 81 9 14 será compreendida pelo batalhão como a transmissão de palavra qual palavra? E a mensagem 27 49 48 79?

In [19]:
C = np.matrix([[2,3], [1,2]])
print(C) 

[[2 3]
 [1 2]]


mensagem 51 81 9 14 :

In [20]:
# mensagem codificada
msg_cod = np.matrix([[51,81], [9,14]])
print(msg_cod)

[[51 81]
 [ 9 14]]


In [21]:
# encontrando a matriz da mensagem decodificada (M), tal que C . M = msg_cod

# Sabe-se que o produto de uma matriz C pela sua inversa C(inversa) = matriz identidade (I)
# Assim, temos:
# C.C(inverse).M = msg_cod.C(inverse)
# I.M = msg_cod.C(inverse)

# Sabe-se ainda que o produto de uma matriz B pela sua matriz identidade (I) é igual a ela mesma: B.I = B
# Assim, temos I.M = M:
# M = msg_cod.C(inverse)

M = np.dot(msg_cod,C.I)
print(M)

[[21.  9.]
 [ 4.  1.]]


In [22]:
# conferindo a resposta
np.dot(M,C)

matrix([[51., 81.],
        [ 9., 14.]])

In [44]:
# texto decodificado
def get_texto_decodificado(mensagem:np.matrix):
  arr_alfabeto = 'A B C D E F G H I J L M N O P Q R S T U V W X Y Z'.split()
  arr_texto = []

  for idx in mensagem.flat:
    arr_texto.append(arr_alfabeto[int(idx)-1])
  
  return ''.join(arr_texto)

In [45]:
# texto da mensagem decodificada
get_texto_decodificado(M)

'VIDA'

 E a mensagem 27 49 48 79?

In [46]:
# mensagem codificada
msg_cod = np.matrix([[27,49], [48,79]])
print(msg_cod)

[[27 49]
 [48 79]]


In [47]:
# mensagem decodificada
M = np.dot(msg_cod,C.I)
print(M)

[[ 5. 17.]
 [17. 14.]]


In [49]:
# conferindo a resposta
np.dot(M,C)

matrix([[27., 49.],
        [48., 79.]])

In [50]:
# texto da mensagem decodificada
get_texto_decodificado(M)

'ERRO'